apiVersion: v1
kind: Service
metadata:
  name: treasury-workflow-service
  namespace: treasury
spec:
  type: ClusterIP
  selector:
    app: treasury-workflow-service
  ports:
    - port: 8080
      targetPort: 8080
