spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/treasury
    username: treasury
    password: treasury
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
